### ISSUE TITLE
Translation of codes ?

### ISSUE THREAD

**Issue by Jimskapt** [quadrifoglio/rust-book-fr#5]
Should we have to translate all the codes ("listing" in English book) in French ?

Example (randomly) :

> ```rust,ignore
> pub fn search<'a>(query: &str, contents: &'a str) -> Vec<&'a str> {
>     let mut results = Vec::new();
> 
>     for line in contents.lines() {
>         if line.contains(query) {
>             results.push(line);
>         }
>     }
> 
>     results
> }
> ```
> 
> <span class="caption">Listing 12-19: Storing the lines that match so we can return them</span>

Or keeping English names are OK for our readers ? (i'm thinking that)

What is your point of view about it ?

**Comment by asettouf** [comment]
I would say keep the snippets in English, especially given that the Rust compiler will yell (or not) in English, not French. In addition, when looking for help (e.g. Stackoverflow), users (including me) find more easily to have an English code than anything else, that's why I would consider it almost a "good practice" to always write code in English.

Last point that I believe is worth mentioning is: do we translate keywords (e.g. garbage collectors) in French? I understand why we would want to do that, and then I would think that having a French-English lexicon would be useful as the French equivalent of "garbage collector" (ramasse miettes) is definitely not as widely known as its English equivalent. This fact possibly being even worst for Rust only terms like "ownership". What do you think?

**Comment by midnya** [comment]
I was wondering the same thing.
I think we should leave it as is, since we almost always have a description of the code right below it: we should translate this description instead in my opinion.

Same goes for compiler errors' examples: since the compiler doesn't offer any other language, let's leave it in English so that people can look back on the book when they get the same error, but if we reference an error in the descriptive text below, let's translate and leave it in backticks to make clear that we literally translated the compiler's output.

I also agree with @asettouf, writing your code in English is especially important in such an open-source oriented language like Rust.

Regarding keywords, I suggest that the first time we encounter them we highlight them, and right after inside paranthesis we translate it, e.g. :

Le *garbage collector* ("ramasse miettes") est...

Whatever solution we end up agreeing on, should we add a side note at the beggining of the book explaining our choices regarding those issues?

**Comment by Jimskapt** [comment]
Yeap, nice, I think we're all in agreement ! @quadrifoglio, are you also OK ?

Thank you for that clarification !

**Comment by quadrifoglio** [comment]
I agree, 100%.
Attempting to translate code and compiler messages would only result in confusion.
For domain-specific technical terms, I think it is worth using both the original English word and the french translation, when it exists.
